// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZG3qJsPuexB52zbQ8aiu7TNwedN7ymXA',
    appId: '1:761510737447:web:56376a88f0282e078f0002',
    messagingSenderId: '761510737447',
    projectId: 'vpr-co-project',
    authDomain: 'vpr-co-project.firebaseapp.com',
    storageBucket: 'vpr-co-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXyP4iKhxHEpHhQc3FzXdpg-E-W57nrwY',
    appId: '1:761510737447:android:7ea33c036a28244f8f0002',
    messagingSenderId: '761510737447',
    projectId: 'vpr-co-project',
    storageBucket: 'vpr-co-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS9N0nbgnK0-J5l3Br7dhJKdHxyiN-IAo',
    appId: '1:761510737447:ios:80bc8db7399ce0978f0002',
    messagingSenderId: '761510737447',
    projectId: 'vpr-co-project',
    storageBucket: 'vpr-co-project.appspot.com',
    iosClientId: '761510737447-d9idtrsqc17i6mv6er7ut9g9no29514d.apps.googleusercontent.com',
    iosBundleId: 'com.vpr.co',
  );
}
